name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Init script
      run: |
        Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
        cd C:\ungoogled-chromium-windows
        python build.py
